/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/Board.vue')['default']
    PieceMiniPreview: typeof import('./src/components/PieceMiniPreview.vue')['default']
    PieceTray: typeof import('./src/components/PieceTray.vue')['default']
    RoleSelectionDialog: typeof import('./src/components/RoleSelectionDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TakeoverConfirmDialog: typeof import('./src/components/TakeoverConfirmDialog.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_366e8768656bbe0600eeda73c2a503f5/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_366e8768656bbe0600eeda73c2a503f5/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_366e8768656bbe0600eeda73c2a503f5/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_366e8768656bbe0600eeda73c2a503f5/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_366e8768656bbe0600eeda73c2a503f5/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_366e8768656bbe0600eeda73c2a503f5/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_366e8768656bbe0600eeda73c2a503f5/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
  }
}
